GET https://bank-erichu.herokuapp.com/api/users

###

POST https://bank-erichu.herokuapp.com/api/user HTTP/1.1
Content-type: application/json

{
    "name": "EricChuko",
    "mobile" : "0559544755",
    "email": "eric@gmail.com",
    "password": "1925"
    
}

###


